apiVersion: apps/v1
kind: Deployment
metadata:
    name: image-validation-admission
    namespace: registry-system
    labels:
        name: image-validation-admission
spec:
    replicas: 1
    selector:
      matchLabels:
        app: image-validation-admission
    template:
        metadata:
            labels:
                app: image-validation-admission
        spec:
            containers:
                - name: webhook
                  image: ghkimkor/image-validation-webhook
                  imagePullPolicy: Always
                  volumeMounts:
                    - name: webhook-certs
                      mountPath: /etc/webhook/certs
                      readOnly: true
                    - name: whitelist
                      mountPath: /etc/webhook/config
                      readOnly: true
            volumes:
                - name: webhook-certs
                  secret:
                    secretName: image-validation-admission-certs
                - name: whitelist
                  configMap:
                    name: image-validation-webhook-whitelist                      
            serviceAccountName: image-validation-webhook