apiVersion: v1
kind: Service
metadata:
    name: image-validation-admission-svc
    namespace: registry-system
    labels:
        name: image-validation-admission
spec:
    ports:
        - name: webhook
          port: 443
          targetPort: 8443
    selector:
        app: image-validation-admission