apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: image-validation-webhook-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: image-validation-webhook-role
subjects:
- kind: ServiceAccount
  name: image-validation-webhook
  namespace: registry-system